config/routes.rb
Rails.application.routes.draw do


  get 'beamers/refresh_all'

  get 'admin/utilities/index'
  post 'admin/utilities/db_upload'
  post 'admin/utilities/set_ews1_endpoint'
  get 'admin/utilities/check_ews1_endpoint'
  get 'admin/utilities/judge_tool_reset'
  get 'admin/utilities/create_and_send_debug_file'


  namespace :admin do
    resources :users do
      collection do
      end
    end
    resources :rounds do
      member do
        post :start
        delete :close
        get :download_ratings
      end
    end
    scope ':dance_team_id' do
      resources :dance_rounds, only: :show
    end
    resources :ratings, only: :update
  end
  namespace :judges do
    resource :dance_round do
      post :accept
    end
    scope ':user_id' do
      resources :dance_rounds, only: %w() do
        member do
          get :status
        end
      end
    end
  end

  post '/admin/rounds/:dance_round_id/:dance_team_id', to: 'admin/rounds#repeat', as: :admin_repeat_dance_round

  resource :round, only: %i(show)
  resource :dance_round, only: %i(show)
  resources :pages, only: :show
  resources :beamers, only: %i(destroy create show index update edit)
  resources :dance_teams, only: %i(show)
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  root to: 'rounds#index'
end

app/views/shared/_navigation.html.haml
.navbar-header
  %button.navbar-toggle.collapsed{data:{target: '#navbar', toggle: 'collapse'}, 'aria-expanded' => 'false', 'type' => 'button'}
    %span.sr-only Toggle navigation
    %span.icon-bar
    %span.icon-bar
    %span.icon-bar
  =link_to 'EWS 2.4.2', root_path, class: 'navbar-brand active'

.collapse.navbar-collapse#navbar{'aria-expanded' => 'false'}
  %ul.nav.navbar-nav
    %li{class: "#{'active' if controller_name == 'users'}" }= link_to 'Teilnehmer', admin_users_path if policy(User).index?
    %li{class: "#{'active' if params[:controller] == 'admin/rounds'}" }= link_to 'Rundenverwaltung', admin_rounds_path if policy(Round).admin_index?
    %li{class: "#{'active' if params[:controller] == 'judges/dance_rounds'}" }= link_to 'Werten', judges_dance_round_path if policy(DanceRound).show?
    %li{class: "#{'active' if controller_name == 'utilities'}"}= link_to 'Tools', admin_utilities_index_path if policy(User).index?
    %li{class: "#{'active' if params[:controller] == 'dance_rounds'}"}= link_to 'Tanzrunde', dance_round_path
    %li{class: "#{'active' if controller_name == 'beamers'}"}= link_to 'Beamer', beamers_path if policy(Beamer).index?



  %ul.nav.navbar-nav.navbar-right
    - if current_user
      %li= link_to " #{current_user.first_name} abmelden", logout_path, method: :delete
    - else
      %li= link_to 'Anmelden', login_path