config/routes.rb
Rails.application.routes.draw do


  get 'beamers/refresh_all'

  get 'admin/utilities/index'
  post 'admin/utilities/db_upload'
  post 'admin/utilities/set_ews1_endpoint'
  get 'admin/utilities/check_ews1_endpoint'
  get 'admin/utilities/judge_tool_reset'
  get 'admin/utilities/create_and_send_debug_file'


  namespace :admin do
    resources :users do
      collection do
      end
    end
    resources :rounds do
      member do
        post :start
        delete :close
        get :download_ratings
      end
    end
    scope ':dance_team_id' do
      resources :dance_rounds, only: :show
    end
    resources :ratings, only: :update
  end
  namespace :judges do
    resource :dance_round do
      post :accept
    end
    scope ':user_id' do
      resources :dance_rounds, only: %w() do
        member do
          get :status
        end
      end
    end
  end

  post '/admin/rounds/:dance_round_id/:dance_team_id', to: 'admin/rounds#repeat', as: :admin_repeat_dance_round

  resource :round, only: %i(show)
  resource :dance_round, only: %i(show)
  resources :pages, only: :show
  resources :beamers, only: %i(destroy create show index update edit)
  resources :dance_teams, only: %i(show)
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  root to: 'rounds#index'
end

app/models/beamer.rb
class Beamer < ActiveRecord::Base
end

app/controllers/beamers_controller.rb
class BeamersController < ApplicationController
  def index
    @beamers = Beamer.all
  end

  def show
      beamer = Beamer.find(params[:id])
      if current_round
        if current_round.round_type.no_dance? || current_round.judges.empty?

          if current_round.round_type.name=="Siegerehrung"
            @round=Round.where(dance_class_id: current_round.dance_class.id, started: true, closed: true).order(:position).last
            if @round.nil?
              @round=current_round
              render :round_name, layout: "beamer"
            else
              @dance_team_result_list = get_dance_team_result_list(@round)
              render :round_ceremony, layout: "beamer"
            end
          else
            @round=current_round
            render :round_name, layout: "beamer"
          end

        else
          if beamer.screen=="moderator"
            @round=current_round
              if @round.dance_rounds.where(round_id: @round.id, started: false, finished: false).count == @round.dance_rounds.count
                @dance_round = DanceRound.where(round_id: @round.id).order(:position).first
                #Es wurde nch keine Tanzrunde gestartet
              elsif current_dance_round
                @dance_round = current_dance_round
                # ich bin in einer tanzrunde

              else
                # Ich bin nach einer Tanzrunde
                @dance_round = DanceRound.where(round_id: @round.id, started: true, finished: true).order(:position).last

              end

            @next_dance_round = DanceRound.where(round_id: @round.id, position: @dance_round.position+1).first

            render :moderator_current, layout: "beamer"


        elsif current_dance_round && (beamer.screen=="current_team" || beamer.screen=="auto")
          render :current_dance_round, layout: "beamer"
        else
          @dance_round = DanceRound.where(round_id: current_round.id, started: true, finished: true).order(:position).last
          if @dance_round
            @round = @dance_round.round
            if beamer.screen=="current_team"
              render :current_dance_round, layout: "beamer"

            elsif @round.round_type.name.include? 'KO'
              render :dance_round_KO, layout: "beamer"
            else
              @dance_team_result_list = @round.dance_teams.uniq.select{|dance_team| dance_team.has_danced?(@round)}.sort_by {|dance_team| dance_team.get_final_result(@round)}.reverse
              render :round_results, layout: "beamer"
            end

          else
            if current_round.dance_rounds.count > 0
              @round=current_round
              @dance_round=@round.dance_rounds.first
              @dance_team_result_list = @round.dance_teams.uniq.select{|dance_team| dance_team.has_danced?(@round)}.sort_by {|dance_team| dance_team.get_final_result(@round)}.reverse
              render :round_results, layout: "beamer"
            else
              render :round_name, layout: "beamer"
            end

          end
        end
        end
      else
        if Round.where(closed: true).count > 0
          render :end_of_tournament, layout: "beamer"
        else
          render :starting_tournament_soon, layout: "beamer"
        end


      end
  end

  def get_dance_team_result_list(round)
    round.dance_teams.uniq.select{|dance_team| dance_team.has_danced?(@round)}.sort_by {|dance_team| dance_team.get_final_result(@round)}.reverse
  end


  def edit
    @beamers = Beamer.find(params[:id])
  end

  def create
    @beamer= Beamer.create screen: "auto"
    redirect_to beamers_path
  end

  def destroy
    Beamer.find(params[:id]).destroy
    redirect_to beamers_path
  end

  def update
    Beamer.find(params[:id]).update_attribute(:screen,params[:screen])
    reload_beamer
    redirect_to(:back)
  end

  def refresh_all
    reload_beamer
    redirect_to beamers_path
  end

  def edit
    @beamer = Beamer.find(params[:id])
    render :remote_control, layout: "beamer"
  end

  private

  def reload_beamer
    $beamer.send 'reload'
  end


end

app/helpers/beamer_helper.rb
module BeamerHelper
end

app/helpers/beamers_helper.rb
module BeamersHelper
end

app/views/beamers/current_dance_round.html.haml
.beamer
  .row
    .col-md-12
      %h1= dance_round_header
  .row
    - current_dance_round.dance_teams.each do |dance_team|
      .dance-team-beamer{class: "#{'col-md-'}#{(12/current_dance_round.dance_teams.size).to_i}"}
        .info-normal=dance_team.startnumber
        - dance_team.dancers.each do|dancer|
          .info-normal=dancer.full_name
        .info-small=dance_team.club.name
  .row
    .col-md-12.center
      =render partial: '/judges/dance_rounds/waiting_table'
#beamer_reload

app/views/beamers/dance_round_KO.html.haml
.beamer
  .row
    .col-md-12
      %h1= dance_round_header
  .row
    - current_dance_round.dance_teams.each do |dance_team|
      .dance-team-beamer{class: "#{'col-md-'}#{(12/current_dance_round.dance_teams.size).to_i}"}
        .info-normal=dance_team.startnumber
        - dance_team.dancers.each do|dancer|
          .info-normal=dancer.full_name
        -if  current_dance_round.is_ko_winner?(dance_team)
          .info-big
            =image_tag 'winner_left.png', width: '96', height: '96'
            = dance_team.get_final_result(@round)
            =image_tag 'winner_right.png', width: '96', height: '96'
        -else
          .info-big= dance_team.get_final_result(@round)
        .info-normal{class: 'red-font'}="#{'TSO malus' if dance_team.tso_malus?(@round)}"
#beamer_reload

app/views/beamers/dance_round_result.html.haml
%h1= dance_round_header
= render partial: '/judges/dance_rounds/waiting_table'
.row.dance_team
  - @dance_round.dance_teams.each do |dance_team|
    .col-sm6
      %p= dance_team.full_name
      %p= " Startnummer: #{dance_team.startnumber}"
      %h2=dance_team.get_final_result(current_dance_round.round)
#beamer_reload

app/views/beamers/index.html.haml
= link_to 'New Beamer', beamers_path, method: :post, class: 'btn btn-primary' if policy(Beamer).create?
= link_to 'refresh all Beamer',beamers_refresh_all_path,class: 'btn btn-primary'
%table.table.table-striped.table-hover
  %thead
    %tr
      %th Beamer
      %th Anzeige
      %th
      %th
  %tbody
  - Beamer.all.each do |beamer|
    %tr
      %td="Beamer #{beamer.id}"
      %td=beamer.screen
      %td
        =link_to 'Result',beamer_path(:id => beamer.id,:screen => 'current_result' ), method: :put, class: 'btn btn-info'
        =link_to 'Team',beamer_path(:id => beamer.id,:screen => 'current_team' ), method: :put, class: 'btn btn-primary'
        =link_to 'Moderator',beamer_path(:id => beamer.id,:screen => 'moderator' ), method: :put, class: 'btn btn-danger'
        =link_to 'Auto',beamer_path(:id => beamer.id,:screen => 'auto' ), method: :put, class: 'btn btn-success'



      %td
        =link_to 'show', beamer_path(beamer), method: :get, class: 'btn btn-success'
        =link_to 'delete', beamer_path(beamer), method: :delete, class: 'btn btn-danger' if policy(Beamer).delete?
        =link_to 'remote', edit_beamer_path(beamer), method: :get, class: 'btn btn-warning'

app/views/beamers/moderator_current.html.haml
.beamer
  .row
    .col-md-12
      %h1= dance_round_header
  .row
    - @dance_round.dance_teams.each do |dance_team|
      .dance-team-beamer{class: "#{'col-md-'}#{(12/current_dance_round.dance_teams.size).to_i}"}
        .info-normal=dance_team.startnumber
        - dance_team.dancers.each do|dancer|
          .info-normal=dancer.full_name
        .info-normal=dance_team.club.name
        -if  current_dance_round.is_ko_winner?(dance_team) && current_dance_round.closed?
          .info-big
            =image_tag 'winner_left.png', width: '96', height: '96'
            = dance_team.get_final_result(@round)
            =image_tag 'winner_right.png', width: '96', height: '96'
        -else
          .info-big= dance_team.get_final_result(@round)
        .info-normal{class: 'red-font'}="#{'TSO malus' if dance_team.tso_malus?(@round)}"
  .row
    .col-md-12.center
      =render partial: '/judges/dance_rounds/waiting_table'
  - if @next_dance_round
    .row
      .col-md-12
        %h1= dance_round_header(@next_dance_round)
    .row
      - @next_dance_round.dance_teams.each do |dance_team|
        .dance-team-beamer{class: "#{'col-md-'}#{(12/@next_dance_round.dance_teams.size).to_i}"}
          .info-normal=dance_team.startnumber
          - dance_team.dancers.each do|dancer|
            .info-normal=dancer.full_name
          .info-normal=dance_team.club.name
          -if  @next_dance_round.is_ko_winner?(dance_team) && @next_dance_round.closed?
            .info-big
              =image_tag 'winner_left.png', width: '96', height: '96'
              = dance_team.get_final_result(@round)
              =image_tag 'winner_right.png', width: '96', height: '96'
          -else
            .info-big= dance_team.get_final_result(@round)
          .info-normal{class: 'red-font'}="#{'TSO malus' if dance_team.tso_malus?(@round)}"
#beamer_reload

app/views/beamers/remote_control.html.haml
.remote_control
  %h1 Remote Controler für Beamer #{@beamer.id}
  %h1 Status: #{@beamer.screen}
  =link_to ' Result',beamer_path(:id => @beamer.id,:screen => 'current_result' ), method: :put, class: 'btn btn-info'
  =link_to ' Dance-Team',beamer_path(:id => @beamer.id,:screen => 'current_team' ), method: :put, class: 'btn btn-primary'
  =link_to 'Moderator',beamer_path(:id => @beamer.id,:screen => 'moderator' ), method: :put, class: 'btn btn-danger'
  =link_to 'Automode',beamer_path(:id => @beamer.id,:screen => 'auto' ), method: :put, class: 'btn btn-success'

=link_to 'back',beamers_path, method: :get, class: 'btn btn-primary'

app/views/beamers/round_ceremony.html.haml
.beamer
  %h1=Round.active.round_type.name + " "+ Round.active.dance_class.name
  %table.table.table-striped
    //- @dance_team_result_list.first(7).each_with_index do |dance_team, index|
    %tr
      %th.center="Platz"
      %th.center="Nummer"
      %th="Paar"
      %th
      %th="Punkte"
    - @dance_team_result_list.each_with_index do |dance_team, index|
      %tr
        - if index > 0 && dance_team.get_final_result(@round) == @dance_team_result_list[index-1].get_final_result(@round)
          %td.center="#{index}."
        - else
          %td.center="#{index+1}."
        %td.center #{dance_team.startnumber}
        %td=" #{dance_team.full_name} "
        %td{class: 'red-font'}="#{'Regelverstoß' if dance_team.tso_malus?(@round)}"
        %td=dance_team.get_final_result(@round)
#beamer_reload

app/views/beamers/round_name.html.haml
.beamer
  %h1.middle="#{@round.round_type.name} #{@round.dance_class.name if @round.dance_class}"
#beamer_reload

app/views/beamers/round_results.html.haml
.beamer
  %h1=dance_round_header
  %table.table.table-striped
    //- @dance_team_result_list.first(7).each_with_index do |dance_team, index|
    %tr
      %th.center="Platz"
      %th.center="Nummer"
      %th="Paar"
      %th
      %th="Punkte"
    - @dance_team_result_list.each_with_index do |dance_team, index|
      %tr
        - if index > 0 && dance_team.get_final_result(@round) == @dance_team_result_list[index-1].get_final_result(@round)
          %td.center="#{index}."
        - else
          %td.center="#{index+1}."
        %td.center #{dance_team.startnumber}
        %td{class: "#{'active_dance_team' if @dance_round.dance_teams.include?(dance_team)}"}= " #{dance_team.full_name} "
        %td{class: 'red-font'}="#{'Regelverstoß' if dance_team.tso_malus?(@round)}"
        %td=dance_team.get_final_result(@round)
#beamer_reload

app/views/beamers/starting_tournament_soon.html.haml
.big_center
  %h1 Turnier startet bald!
#beamer_reload